# serverless.yml

yourProjectName:
  component: "@sls-next/serverless-component@3.1.0"
  inputs:
    minifyHandlers: true
    build:
      postBuildCommands:
        - PDIR=node_modules/.prisma/client/;
          LDIR=.serverless_nextjs/api-lambda/;
          TDIR=node_modules/.prisma/client/;
          if [ "$(ls -A $LDIR)" ]; then
          mkdir -p $LDIR$TDIR;
          cp "$PDIR"query-engine-rhel-* $LDIR$TDIR;
          cp "$PDIR"schema.prisma $LDIR$TDIR;
          fi;
        - PDIR=node_modules/.prisma/client/;
          LDIR=.serverless_nextjs/default-lambda/;
          TDIR=node_modules/.prisma/client/;
          if [ "$(ls -A $LDIR)" ]; then
          mkdir -p $LDIR$TDIR;
          cp "$PDIR"query-engine-rhel-* $LDIR$TDIR;
          cp "$PDIR"schema.prisma $LDIR$TDIR;
          fi;
